apiVersion: v1
data:
  orderer.imfreemobile.com-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNHekNDQWNLZ0F3SUJBZ0lSQUlZWjFIa1lsTExWZHpIUlAyc3NOQk13Q2dZSUtvWkl6ajBFQXdJd2N6RUwKTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXhGakFVQmdOVkJBY1REVk5oYmlCRwpjbUZ1WTJselkyOHhHVEFYQmdOVkJBb1RFR2x0Wm5KbFpXMXZZbWxzWlM1amIyMHhIREFhQmdOVkJBTVRFMk5oCkxtbHRabkpsWlcxdlltbHNaUzVqYjIwd0hoY05NVGt3T1RJNU1ETXdOakF3V2hjTk1qa3dPVEkyTURNd05qQXcKV2pCZE1Rc3dDUVlEVlFRR0V3SlZVekVUTUJFR0ExVUVDQk1LUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnhNTgpVMkZ1SUVaeVlXNWphWE5qYnpFaE1COEdBMVVFQXhNWWIzSmtaWEpsY2k1cGJXWnlaV1Z0YjJKcGJHVXVZMjl0Ck1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVJiM0lUWkVBOFRnV0RydGZ5b25PSzhEMkEyQk0Kc0xqOHRsSUV2alppYklKOTFPeUdUeGt4Q1NBeHI5UG51eFpRRG93RHhEVHFTVFJhYmxnSExEZndNYU5OTUVzdwpEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3S3dZRFZSMGpCQ1F3SW9BZ3J3S3IwY00vCnB4QjdkbGRqN0p5OVJYb1NpQjNHSjBiNVlyNUdPakdKQzlnd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ1lYSmwKV00rRXhsZ3hna3BtMUN5R1BXU3Z6RVp1R2ZtQVdtdEZtcEpad0xRQ0lEcGsvckhLY05FejFFVnIxRHhSYlh3Ywp2MWMrdTRHd0VkOTB0Z29Nb0M4KwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
kind: Secret
metadata:
  creationTimestamp: "2019-09-29T05:14:12Z"
  name: o-cert-orderer-msp-signcerts
  namespace: default
  resourceVersion: "13334"
  selfLink: /api/v1/namespaces/default/secrets/o-cert-orderer-msp-signcerts
  uid: ab4273d1-e6cc-4a12-8c29-77f4e0992a6b
type: Opaque
