apiVersion: v1
data:
  Admin_org1.imfreemobile.com-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNPRENDQWQrZ0F3SUJBZ0lRUFBRTlc0Um9LemtIeStvU1gwSHJ3REFLQmdncWhrak9QUVFEQWpCOU1Rc3cKQ1FZRFZRUUdFd0pWVXpFVE1CRUdBMVVFQ0JNS1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ4TU5VMkZ1SUVaeQpZVzVqYVhOamJ6RWVNQndHQTFVRUNoTVZiM0puTVM1cGJXWnlaV1Z0YjJKcGJHVXVZMjl0TVNFd0h3WURWUVFECkV4aGpZUzV2Y21jeExtbHRabkpsWlcxdlltbHNaUzVqYjIwd0hoY05NVGt3T1RNd01UTXlOREF3V2hjTk1qa3cKT1RJM01UTXlOREF3V2pCeE1Rc3dDUVlEVlFRR0V3SlZVekVUTUJFR0ExVUVDQk1LUTJGc2FXWnZjbTVwWVRFVwpNQlFHQTFVRUJ4TU5VMkZ1SUVaeVlXNWphWE5qYnpFUE1BMEdBMVVFQ3hNR1kyeHBaVzUwTVNRd0lnWURWUVFECkRCdEJaRzFwYmtCdmNtY3hMbWx0Wm5KbFpXMXZZbWxzWlM1amIyMHdXVEFUQmdjcWhrak9QUUlCQmdncWhrak8KUFFNQkJ3TkNBQVJ6LzlpR3FuODhCbHo2a3lIeHNNU2hKZHNwTkJ1UFIrSjdIQnR4Ukx1Vm9YRTJFMG5xai9DOQovZ3RKNEVMaG1pVFRRbUFWbXluR3N4ZzBFUTFkeFpiV28wMHdTekFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEClZSMFRBUUgvQkFJd0FEQXJCZ05WSFNNRUpEQWlnQ0NzbS8yRUgwUktOUjFQZkJCdCtmN0puUnJsbGNEVFEyK3QKT1djNEE0TXZQVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFCdlRNSlpoNkd3SHhZWDhjZEQ2TnlveFE1U1ZOagp1WlQrZWxLTncwbi9KUUlnYncrYUhRQTc4V1pEWmRMdlFNU200R0dSUXFNMlFIVStYS2lnb0hqOTk2QT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: "2019-09-30T13:34:58Z"
  name: p-cert-msp-tlscacerts
  namespace: default
  resourceVersion: "620"
  selfLink: /api/v1/namespaces/default/secrets/p-cert-msp-tlscacerts
  uid: ec82d89e-0521-4bc7-9634-d389ca00beec
type: Opaque
