apiVersion: v1
data:
  tlsca.org1.imfreemobile.com-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNiVENDQWhTZ0F3SUJBZ0lSQUtHMlZORnlaWmFGRXkvdHJ6alJ4TVV3Q2dZSUtvWkl6ajBFQXdJd2dZQXgKQ3pBSkJnTlZCQVlUQWxWVE1STXdFUVlEVlFRSUV3cERZV3hwWm05eWJtbGhNUll3RkFZRFZRUUhFdzFUWVc0ZwpSbkpoYm1OcGMyTnZNUjR3SEFZRFZRUUtFeFZ2Y21jeExtbHRabkpsWlcxdlltbHNaUzVqYjIweEpEQWlCZ05WCkJBTVRHM1JzYzJOaExtOXlaekV1YVcxbWNtVmxiVzlpYVd4bExtTnZiVEFlRncweE9UQTVNamt3TXpBMk1EQmEKRncweU9UQTVNall3TXpBMk1EQmFNSUdBTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNCTUtRMkZzYVdadgpjbTVwWVRFV01CUUdBMVVFQnhNTlUyRnVJRVp5WVc1amFYTmpiekVlTUJ3R0ExVUVDaE1WYjNKbk1TNXBiV1p5ClpXVnRiMkpwYkdVdVkyOXRNU1F3SWdZRFZRUURFeHQwYkhOallTNXZjbWN4TG1sdFpuSmxaVzF2WW1sc1pTNWoKYjIwd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTMFpNN3BBR2s2T3dTMmFFV2NnSXEyU0RBQgpiZEUzcnN6UWRCK3NPN1Q0cTNmTVc1dUo4bXQxU3lSM1VrR2Q0emdBdkV3bVZvQ3N1WnhiK0JNelFvMVBvMjB3CmF6QU9CZ05WSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRkJ3TUIKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3S1FZRFZSME9CQ0lFSUVQL2hWVE83ZnNTTENGQW9BdytoQ3BaZFdhaQpnNDhzWjN6QS9MRU0vb01YTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUVzNDFYa2NUaE92WjlnZjI1WENhbFFtCkNwZGhSdGI3RXFNSmhmdkQ2WjhnQWlCNnpVQk5IOE1BNFpJbHVIMXJJUG9ZdG16YnRLb2VxZE1pSzZVWkdtTTAKZ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
kind: Secret
metadata:
  creationTimestamp: "2019-09-29T05:14:13Z"
  name: p-cert-peer-msp-tlscacerts
  namespace: default
  resourceVersion: "13352"
  selfLink: /api/v1/namespaces/default/secrets/p-cert-peer-msp-tlscacerts
  uid: 67907b97-3d46-4e82-8814-c06b4e0b6a20
type: Opaque
