apiVersion: v1
data:
  User1_org1.imfreemobile.com-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNPVENDQWQrZ0F3SUJBZ0lRTmozOVJLTjliTGVjRTdibmFsUXJIekFLQmdncWhrak9QUVFEQWpCOU1Rc3cKQ1FZRFZRUUdFd0pWVXpFVE1CRUdBMVVFQ0JNS1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ4TU5VMkZ1SUVaeQpZVzVqYVhOamJ6RWVNQndHQTFVRUNoTVZiM0puTVM1cGJXWnlaV1Z0YjJKcGJHVXVZMjl0TVNFd0h3WURWUVFECkV4aGpZUzV2Y21jeExtbHRabkpsWlcxdlltbHNaUzVqYjIwd0hoY05NVGt3T1RJNU1ETXdOakF3V2hjTk1qa3cKT1RJMk1ETXdOakF3V2pCeE1Rc3dDUVlEVlFRR0V3SlZVekVUTUJFR0ExVUVDQk1LUTJGc2FXWnZjbTVwWVRFVwpNQlFHQTFVRUJ4TU5VMkZ1SUVaeVlXNWphWE5qYnpFUE1BMEdBMVVFQ3hNR1kyeHBaVzUwTVNRd0lnWURWUVFECkRCdFZjMlZ5TVVCdmNtY3hMbWx0Wm5KbFpXMXZZbWxzWlM1amIyMHdXVEFUQmdjcWhrak9QUUlCQmdncWhrak8KUFFNQkJ3TkNBQVJuaHRER0x6UXRITUlDQnJhU1dmQU1BazVERkZCbkdwOFQwaUdGa0F5d0Npcks3NVcyeWxhVQp5L2k4WjVuRjVxVUZMRWlwb1gxMkNRUlhPZ2UyV3lTTm8wMHdTekFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEClZSMFRBUUgvQkFJd0FEQXJCZ05WSFNNRUpEQWlnQ0FYOThjdm1rRStreUtyZEUrZCsrS0tTSlk0Sjd3eVZlbSsKbUdqOGo2dHlhREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBcHJCVXduNE9CVjVPSDVsNzJ3T2Z5YTVWVHVqVAp6c3B4SkZXdFlvemRXQVlDSURzTWNXOHlpcHlIS0x5OVNyWllLVjZLQXVHQnJuZWloTUlxRDlOQWRvRkgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: "2019-09-29T06:51:16Z"
  name: p-cert-user1-msp-signcerts
  namespace: default
  resourceVersion: "21908"
  selfLink: /api/v1/namespaces/default/secrets/p-cert-user1-msp-signcerts
  uid: 26a7cc87-9bc9-45e1-9e1e-dfa18e86a71c
type: Opaque
