apiVersion: v1
data:
  Admin_org1.imfreemobile.com-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNPVENDQWVDZ0F3SUJBZ0lSQUxkNlhKWkVuclcrRGloTzREZkNRUTR3Q2dZSUtvWkl6ajBFQXdJd2ZURUwKTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXhGakFVQmdOVkJBY1REVk5oYmlCRwpjbUZ1WTJselkyOHhIakFjQmdOVkJBb1RGVzl5WnpFdWFXMW1jbVZsYlc5aWFXeGxMbU52YlRFaE1COEdBMVVFCkF4TVlZMkV1YjNKbk1TNXBiV1p5WldWdGIySnBiR1V1WTI5dE1CNFhEVEU1TURreU9UQXpNRFl3TUZvWERUSTUKTURreU5qQXpNRFl3TUZvd2NURUxNQWtHQTFVRUJoTUNWVk14RXpBUkJnTlZCQWdUQ2tOaGJHbG1iM0p1YVdFeApGakFVQmdOVkJBY1REVk5oYmlCR2NtRnVZMmx6WTI4eER6QU5CZ05WQkFzVEJtTnNhV1Z1ZERFa01DSUdBMVVFCkF3d2JRV1J0YVc1QWIzSm5NUzVwYldaeVpXVnRiMkpwYkdVdVkyOXRNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemowREFRY0RRZ0FFc1VKTFYzVXV0RlNLRlZENWxaZUtVRmN5bk1IbXZFYTROT0plck9XcG9HUUdERVJKaVNKLwpTeSt1a3RqeG9Bd3Y2WU8xT0VkVzNaY2t3c3ZaWlhMRTFxTk5NRXN3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHCkExVWRFd0VCL3dRQ01BQXdLd1lEVlIwakJDUXdJb0FnRi9mSEw1cEJQcE1pcTNSUG5mdmlpa2lXT0NlOE1sWHAKdnBoby9JK3JjbWd3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnVWtRb0Y5RmRTOFhPaXp5c1dBOFpmakoyT2FNQwpBSGJvZDBwK0RZMU5PRGtDSUVQR0VLWWwxRmVEQ01PMUgxRjd0eVNEeFA2K1RRRWJJMHprUmZCUTNZd2QKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: "2019-09-29T06:51:15Z"
  name: p-cert-msp-tlscacerts
  namespace: default
  resourceVersion: "21890"
  selfLink: /api/v1/namespaces/default/secrets/p-cert-msp-tlscacerts
  uid: b63c6fdd-14fa-4cab-b75b-df386697da61
type: Opaque
